name: Run Custom Script

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run custom script
      run: |
        #cd path/to/script/directory
        #echo "Hello World!"
        # 执行脚本文件
        sudo sh ./hello.sh
